# sshagentca example settings file

# certificate validity period in minutes periods of more than 24 hours are
# not permitted by this implementation. certificates with the 'forever'
# validity string are also not supported.
validity: 180

# organisation name, used in certificate identifer (which shows in
# /var/log/auth.log on debian derivate hosts authorising user certificates; also
# shows in `ssh-agent -l` on user hosts
organisation: acmeinc

# banner, used to greet connecting users
banner: |
    acmeinc ssh user certificate service

# extensions, certificate "allow" extensions as set out in "Extensions" at
# https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL.certkeys?annotate=HEAD
# these set the permissions given to users connecting to remote servers
# whose connections are authorised by this service.
extensions:
    # "no-presence-required": "", // only U2F/Fido, not supported here
    permit-agent-forwarding: ""
    permit-port-forwarding: ""
    permit-pty: ""
    # permit-X11-forwarding: ""
    # permit-user-rc: ""

# user_principals, a list of configuration blocks by user, with name,
# ssh key fingerprint and the principals to be inserted in the
# certificate. To be valid, the fingerprints must exist in the
# authorized_keys file provided to the program.
# This structure can also be used to allow someone to have two key
# registrations to receive different principal assignments
# Note that zero-length principals are valid for *any* username (and are
# therefore not support). Fingerprints are ssh key sha256 hashes
# fingerprints may be listed by ssh-keygen -l -f <filename>
user_principals:
    -
        name: jane
        fingerprint: SHA256:R9cdULU8AvYJxyqX6Kws6Rgl+cjHD70zGCbaxFRRDi8
        principals:
            - web
            - database
            - root

    -
        name: john
        fingerprint: SHA256:Ar7p/R9HO/Dwl5LtA3bZpRvHBOvKLkAtHtJyTDUOLqg
        principals:
            - web
            - database
    

